### ISSUE TITLE
Readme Review

### ISSUE THREAD

**Issue by tayyab-10** [abubakarmunir712/dsa-final-project#2]
I’d rate this README 9/10. It’s thorough and detailed, but adding visuals and fixing minor errors could make it perfect!
What I like most in your Readme File is the Comprehensive Table of Contents. It is a fantastic addition, making it easy to navigate through different sections. 
Overall, great job on creating such a comprehensive README!

**Comment by aabr2612** [comment]
Thank you for getting me noticed! I have fixed the README file, you can check it again!

**Comment by aabr2612** [comment]
Thanks for getting me noticed! I have updated the README file you can visit and review again!

**Comment by aabr2612** [comment]
Thanks for getting me noticed! I have updated the README file you can visit and review again!
